# Setup
title:        HCHS Athletic Association
tagline:      Your one stop shop for Hunter Athletics news
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Gabriel Buchdahl
  url:        hunterschools.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

#categories
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
